import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    os.makedirs(directory, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{directory}/AI_Trip_Plan_{timestamp}.md"

    markdown_content = f"""# 🌍 AI Travel Plan
**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
---

{response_text}

---

*This travel plan was generated by AI.*"""

    try:
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        return filename
    except Exception as e:
        print(f"Error saving file: {e}")
        return None
